[package]
name = "run0"
version = "0.1.0"
edition = "2021"
authors = ["Polytech Montpellier - DevOps"]

[dependencies]
clap = { version = "3.0.5", features = ["derive"] }
container = { path = "container" }

[workspace]
members = [
        "container"
]